### ISSUE TITLE
incompatibility with seuratobject 5.0.2

### ISSUE THREAD

**Issue by abraham-abin13** [cz0316/HEARTSVG#3]
Hi, 

Your pacakge is phenomenal and I have gotten good results with my dataset. 

SeuratObjects got updated to version 5.0.2 recently and I was previously using 5.0.1. 

The coordinates slot has been modified in the most recent version which is incompatible with "seurat.trans" function. Specifically, the issue is this line: 
```

  coor=data.frame(object@images[[Images(object)]]@coordinates,
                  cell= rownames(object@images[[Images(object)]]@coordinates))

```
------- 
Running the command:
` object@images[[Images(object)]]@coordinates` 

on the SeuratObject version 5.0.1, yielded this: 

```
                   tissue row col imagerow imagecol
AACAATGGAACCACAT-1      1  54  32     1293      657
AACACCAGCCTACTCG-1      1  31  39      869      732
AACACCATTCGCATAC-1      1  53 139     1275     1797
```

for version 5.0.2 yielded an error: 
`"no slot of name "coordinates" for this object of class "VisiumV2"
`
Indeed, in the new seurat object this slot is no longer present. However, there is a slot for coordinate located as such: 

`seu@images[["slice1"]]@boundaries[["centroids"]]@coords. `

But this output (see below) is not the same as the 'coordinates' output. 

```
        x    y
[1,] 1293  657
[2,]  869  732
[3,] 1275 1797

```

---- 
**Since the downstream code uses "row" and "col" instead of "imagerow" and "imagecol", does it matter if i modify the code to use "imagerow" and "imagecol"??** 

Thank you! Hope my explanation is clear!

**Comment by cz0316** [comment]
Yes, you can use "imagerow" and "imagecol" instead of "row" and "col". However, you will need to rename the column names to "row" and "col" before running the downstream code. If you use "imagerow" and "imagecol" as column names directly, the code may produce errors, as other functions rely on "row" and "col" as column names.

Thank you for pointing this out! I will update the code to address this issue in the next version.
